server:
  port: 80
#  context-path: /web
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.170:8888/eureka/
ribbon:
  eureka:
    enabled: true
spring:
  application:
    name: yxw-pc

  thymeleaf:
      prefix: classpath:/templates/yxw/
  resources:
      static-locations: classpath:/static/,classpath:/public/
  devtools:

    restart:
      enabled: true
      exclude: WEB-INF/**,src/main/java,src/main/resources/*.yml
  mvc:
    favicon:
      enabled: false



