server:
  port: 8011
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.170:8888/eureka/
spring:
  application:
    name: yxw-pay
 ##activemq连接信息
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false

  redis:
    host: 192.168.110.170
    password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
        name: yxw_pay
        url: jdbc:mysql://118.31.9.5:3306/yxw_pay
        username: niping
        password: 123456
        tomcat-jdbc: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20




mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yxw.entity
