server:
  port: 8002
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.170:8888/eureka/
spring:
  application:
    name: yxw-message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: AaaNeei@163.com
    password: yxw888message
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
########################################
MESSAGES_QUEUE: messages_email
msg:
  subject: 游学网用户
  text: 恭喜您的账户{},注册成功!请登录www.yxw.com参与活动!