server:
  port: 8002
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.110.170:8888/eureka/
spring:
  application:
    name: yxw_message
  activemq:
    broker-url: tcp://localhost:8161
    in-memory: true
    pool:
      enabled: false
  mail:
    host: smtp.163.com
    username: AaaNeei@163.com
    password: AaaNeei
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true
########################################
MESSAGES_QUEUE: messages_email
msg:
  subject: 蚂蚁课堂|每特教育提示您，会员注册成功邮件。
  text:  恭喜您的账户{},注册成功!蚂蚁课堂|每特教育 上海每特教育科技有限公司 www.itmayiedu.com

